# Generated by Django 4.2.4 on 2023-09-06 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='position',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
